services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      # outside : inside
      - 5432:5432
    volumes:
      # - pgdata:/var/lib/postgresql/data
      # below is anonymous version of above
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      # - mongodata:/var/lib/mongodb/data
      # below is anonymous version of above
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

# # comment out if using anon volumes above
# volumes:
#   pgdata:
#   mongodata:
